### ISSUE TITLE
Issue: Icon request

### ISSUE THREAD

**Issue by zeelsheladiya** [Klarr-Agency/Circum-Icons#10]
**Please verify these criteria before summiting your issue**
- [ x ] I look through all icons at circumicons.com to see if there is no icon with the same use case.
- [ x ] Explicit content is not allowed

**Describe the icon you'd like**
 I want to add more icons like tech companies icons, basic feature icons, monument icons, currency icons, and many more.

**Additional context**
here I am adding a screenshot of my hand-drawing icon idea so you can make a better understanding.
![IMG_20221021_001641](https://user-images.githubusercontent.com/46935793/197111332-bdb97bca-1dfd-46dc-bee5-c04dc4176999.jpg)
![IMG_20221021_001650](https://user-images.githubusercontent.com/46935793/197111337-3c36d29f-a795-48aa-9e94-95aa4465b3da.jpg)
![IMG_20221021_001700](https://user-images.githubusercontent.com/46935793/197111352-fdff7811-3428-4fdb-adea-2ed608729d8f.jpg)

**Keyword**
Google, Microsoft, Apple, Amazon, Pyramid, Eiffel Tower, Statue of Unity, Statue of Liberty, Rupee, Pound, Euro, Yuan, Flag, Taj Mahal, Football, Golf, Earth, Torch, Screenshot, Lock Orientation, Scanner, Reading mode, Cast, Vibrate, Key...

**Comment by Klarr-Agency** [comment]
Hi @zeelsheladiya,
I don't know if you have seen it already, but our contribution guide his now accessible [here](https://github.com/Klarr-Agency/Circum-Icons/blob/main/CONTRIBUTING.md)

Have a nice day!😄

**Comment by zeelsheladiya** [comment]
I got your update. The thing is, i am student. For me it is taking time. But i started the icons work. It will gonna take some time though but i will do it 100%. Thank you

**Comment by Klarr-Agency** [comment]
no worries, take your time. I just didn't want you to wait for me. 😄

**Comment by zeelsheladiya** [comment]
Hi Guillaume, almost all the icons are ready. but just to make sure that my icons are valid or not so I just committed one icon named Yuan. So, Let me know. is it a valid icon? or I need to do changes. After that, I will upload other icons. Thank you.

**Comment by zeelsheladiya** [comment]
Hi Guillaume, now my exams are completed, I was sick so I could focus on this project. But now I am fit and fine. I was trying to make SVG but I am confused about the export setting. I recently shifted from windows to MacBook. So for the software, I only have 2 options right now to design SVG. 
1. affinity designer 2 (free trial), 
3. Inkscape

So, can you tell me the export setting for this software, please? 
Thank you

**Comment by Klarr-Agency** [comment]
Feel free to open an other issue in the futur !
