### ISSUE TITLE
Project description typo

### ISSUE THREAD

**Issue by samuei** [Klarr-Agency/Circum-Icons#16]
**Describe the bug**
In the Github "About" section, "Every icons" should read "Every icon".

**To Reproduce**
1. Click "Code" above
2. Look on the right

**Additional context**
Will require a repository admin to change via Github's web interface (gear icon next to "About")

**Comment by Klarr-Agency** [comment]
Thank you @samuei ! English is not our first language at Klarr Agency. 😋 If you find something else in the documentation feel free to open another issue or a PR.

**Comment by samuei** [comment]
Happy to help!
