### ISSUE TITLE
Npm package type definitions:

### ISSUE THREAD

**Issue by melosh101** [Klarr-Agency/Circum-Icons#23]
**Is your feature request related to a problem? Please describe.**
Using the packages in typescript can be troublesome since the package doesn't include a type definition.

**Describe the solution you'd like**
I'd like to add type definitions to all the packages

**Describe alternatives you've considered**
The types could also be added to the definitely typed repo, but in opinion having the type definitions in the main package is easier and doesn't require a third party

**Additional context**
When I get the time I will create a PR with functional type definitions

**Comment by Klarr-Agency** [comment]
Hi @melosh101,
Adding types would be a great contribution to the project. Thank you for your willingness to help!  I will do security update at the same time.
