### ISSUE TITLE
Monorepo structure

### ISSUE THREAD

**Issue by dogagenc** [Klarr-Agency/Circum-Icons#4]
I've seen that you maintain multiple repositories for each library/framework. It's not necessary to make changes on each repo when you make updates/changes. This problem could be easily solved by using [Lerna](https://lerna.js.org/docs/introduction).

Project structure would be:
```
-- packages
  -- circum-icons-core
  -- circum-icons-svelte
  -- circum-icons-react
  -- circum-icons-vue
```

Lerna would deal publishing packages to proper npm registries. 

----

## Another idea:

Instead of creating and editing `displayIcons.js` file manually from svg files, you could write a build script that generates `displayIcons.js` file by extracting both names and direct inner html of svg files. So, it would be easy to add new icons just by adding files to `svg` folder and build `circum-icons-core` package.

**Comment by Klarr-Agency** [comment]
I didn't know Lerna, but that's really what I needed. I'll implement those two ideas for sure.


Can I ask you where did you find this repo :)

**Comment by dogagenc** [comment]
> I didn't know Lerna, but that's really what I needed. I'll implement those two ideas for sure.
> 
> Can I ask you where did you find this repo :)
> 
> Thank you again for your time!

Great! I think this two feature will help you to save your time for future. :)

We've created a browser extension called [Designer Daily Report](https://designerdailyreport.com/). I'm the main developer of it. I've seen your project in our `Library` section in Designer Daily Report. :)

**Comment by Klarr-Agency** [comment]
@dogagenc It looks really good! Again, thank you for your suggestion.
